# Generated by Django 5.2.17 on 2026-09-23 22:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('organization_type', models.CharField(choices=[('GOVERNMENT', 'Government'), ('NGO', 'Non-governmental organization'), ('DONOR', 'Donor'), ('FOUNDATION', 'Foundation'), ('HEALTHCARE_PROVIDER', 'Healthcare provider'), ('INSURER', 'Insurer'), ('PAYMENT_PROVIDER', 'Payment provider'), ('DEVELOPMENT_PARTNER', 'Development partner'), ('PROFESSIONAL_BODY', 'Professional body'), ('OTHER', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING_VERIFICATION', 'Pending verification'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive')], default='PENDING_VERIFICATION', max_length=30)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organization',
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['status'], name='organizatio_status_3d172d_idx'), models.Index(fields=['organization_type'], name='organizatio_organiz_b4644e_idx'), models.Index(fields=['name'], name='organizatio_name_bcc2ee_idx')],
            },
        ),
    ]
