# Generated by Django 5.2.17 on 2026-09-29 21:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('PRIMARY_HEALTH_CENTRE', 'Primary health centre'), ('CLINIC', 'Clinic'), ('SPECIALIST_CENTRE', 'Specialist centre'), ('DIAGNOSTIC_CENTRE', 'Diagnostic centre'), ('PHARMACY', 'Pharmacy'), ('OTHER', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING_VERIFICATION', 'Pending verification'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive')], default='PENDING_VERIFICATION', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='organizations.organization')),
            ],
            options={
                'db_table': 'facility',
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['organization'], name='facility_organiz_3e61e3_idx'), models.Index(fields=['status'], name='facility_status_ef80c9_idx'), models.Index(fields=['facility_type'], name='facility_facilit_153cbd_idx'), models.Index(fields=['name'], name='facility_name_1d2be4_idx')],
            },
        ),
    ]
