# Generated by Django 5.2.17 on 2026-09-29 21:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_facility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareProfessional',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('profession', models.CharField(choices=[('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('MIDWIFE', 'Midwife'), ('PHARMACIST', 'Pharmacist'), ('LABORATORY_SCIENTIST', 'Laboratory scientist'), ('RADIOGRAPHER', 'Radiographer'), ('PHYSIOTHERAPIST', 'Physiotherapist'), ('DENTIST', 'Dentist'), ('HEALTH_INFORMATION_MANAGER', 'Health information manager'), ('COMMUNITY_HEALTH_PRACTITIONER', 'Community health practitioner'), ('OTHER', 'Other')], max_length=50)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('license_status', models.CharField(choices=[('PENDING_VERIFICATION', 'Pending verification'), ('VERIFIED', 'Verified'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked')], default='PENDING_VERIFICATION', max_length=30)),
                ('status', models.CharField(choices=[('PENDING_VERIFICATION', 'Pending verification'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive')], default='PENDING_VERIFICATION', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='healthcare_professional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'healthcare_professional',
                'ordering': ['user__last_name', 'user__first_name', 'id'],
                'indexes': [models.Index(fields=['profession'], name='healthcare__profess_9f2f56_idx'), models.Index(fields=['license_status'], name='healthcare__license_84e326_idx'), models.Index(fields=['status'], name='healthcare__status_72517b_idx')],
            },
        ),
    ]
